[2024-09-10T01:08:05.801+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_csv_dag.extract_postgres_to_csv scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-10T01:08:05.809+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_csv_dag.extract_postgres_to_csv scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-10T01:08:05.810+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2024-09-10T01:08:05.821+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_postgres_to_csv> on 2024-09-09 00:00:00+00:00
[2024-09-10T01:08:05.834+0000] {standard_task_runner.py:57} INFO - Started process 176 to run task
[2024-09-10T01:08:05.841+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_csv_dag', 'extract_postgres_to_csv', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_csv_dag.py', '--cfg-path', '/tmp/tmpo_9wbn8b']
[2024-09-10T01:08:05.848+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask extract_postgres_to_csv
[2024-09-10T01:08:05.949+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_to_csv_dag.extract_postgres_to_csv scheduled__2024-09-09T00:00:00+00:00 [running]> on host d07c2d7229ec
[2024-09-10T01:08:06.201+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fikri' AIRFLOW_CTX_DAG_ID='postgres_to_csv_dag' AIRFLOW_CTX_TASK_ID='extract_postgres_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-09-10T01:08:06.214+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2024-09-10T01:08:06.218+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_csv_dag.py", line 16, in postgres_to_csv
    df = pg_hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 218, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-09-10T01:08:06.231+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=***_to_csv_dag, task_id=extract_***_to_csv, execution_date=20240909T000000, start_date=20240910T010805, end_date=20240910T010806
[2024-09-10T01:08:06.242+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task extract_***_to_csv (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 176)
[2024-09-10T01:08:06.307+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-10T01:08:06.329+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
